import { type DashboardSnapshot, DEFAULT_API_BASE_URL } from '@shiplead/shared';
import {
  Badge,
  Briefcase,
  Building2,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Inbox,
  ListTodo,
  Target,
  UserRound,
} from '@shipshitdev/ui';

export const dynamic = 'force-dynamic';

async function getDashboard(): Promise<DashboardSnapshot | null> {
  try {
    const response = await fetch(
      `${process.env.NEXT_PUBLIC_SHIPLEAD_API_URL ?? DEFAULT_API_BASE_URL}/dashboard`,
      {
        cache: 'no-store',
      },
    );

    if (!response.ok) return null;
    return (await response.json()) as DashboardSnapshot;
  } catch {
    return null;
  }
}

function Metric(props: { label: string; value: string; detail: string }) {
  return (
    <Card>
      <CardHeader>
        <CardDescription>{props.label}</CardDescription>
        <CardTitle className="text-4xl tracking-normal">{props.value}</CardTitle>
      </CardHeader>
      <CardContent className="text-sm text-secondary">{props.detail}</CardContent>
    </Card>
  );
}

export default async function Home() {
  const dashboard = await getDashboard();

  if (!dashboard) {
    return (
      <main className="mx-auto flex min-h-screen max-w-5xl items-center justify-center px-6 py-16">
        <Card className="max-w-2xl">
          <CardHeader>
            <CardTitle>Shiplead needs the API running</CardTitle>
            <CardDescription>
              Start <code className="rounded bg-primary px-2 py-1">bun run dev:api</code> and
              refresh this page.
            </CardDescription>
          </CardHeader>
          <CardContent className="text-sm text-secondary">
            Expected URL: {process.env.NEXT_PUBLIC_SHIPLEAD_API_URL ?? DEFAULT_API_BASE_URL}
          </CardContent>
        </Card>
      </main>
    );
  }

  return (
    <main className="mx-auto max-w-7xl px-6 py-12">
      <section className="grid gap-8 lg:grid-cols-[1.3fr_1fr]">
        <div className="space-y-5">
          <div className="text-xs uppercase tracking-[0.22em] text-muted">Shiplead</div>
          <h1 className="max-w-3xl text-5xl font-semibold leading-[1.02]">
            One agentic CRM for every open-source product, offer, and founder-led sequence.
          </h1>
          <p className="max-w-2xl text-lg text-secondary">
            Desktop-first operator cockpit, local-first API, shared contacts and companies, native
            sequencing, inbox triage, and channel-aware outreach across email, X, and LinkedIn
            copilot.
          </p>
          <div className="flex flex-wrap gap-3">
            <Badge>Self-hosted</Badge>
            <Badge>Multi-project</Badge>
            <Badge>Email + X automation</Badge>
            <Badge>LinkedIn copilot</Badge>
          </div>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Workspace Snapshot</CardTitle>
            <CardDescription>{dashboard.workspace.name}</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4 text-sm text-secondary">
            {dashboard.projects.map((project) => (
              <div key={project.id} className="rounded-2xl border border-border bg-primary p-4">
                <div className="font-medium text-primary">{project.name}</div>
                <div className="mt-2">{project.description}</div>
              </div>
            ))}
          </CardContent>
        </Card>
      </section>

      <section className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <Metric
          label="Contacts"
          value={String(dashboard.metrics.contactCount)}
          detail="People shared across products, offers, and channel plays."
        />
        <Metric
          label="Companies"
          value={String(dashboard.metrics.companyCount)}
          detail="Accounts tracked once, reused everywhere."
        />
        <Metric
          label="Open Tasks"
          value={String(dashboard.metrics.openTaskCount)}
          detail="Next best action queue for the founder/operator."
        />
        <Metric
          label="Pipeline Value"
          value={`$${dashboard.metrics.pipelineValue.toLocaleString()}`}
          detail="Current value across open opportunities."
        />
      </section>

      <section className="mt-10 grid gap-6 xl:grid-cols-3">
        <Card>
          <CardHeader>
            <div className="flex items-center gap-3">
              <ListTodo className="h-5 w-5 text-accent" />
              <CardTitle>New Task Queue</CardTitle>
            </div>
            <CardDescription>Generated by inbox, sequences, and manual ops.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {dashboard.tasks.map((task) => (
              <div key={task.id} className="rounded-2xl border border-border bg-primary p-4">
                <div className="flex items-center justify-between gap-3">
                  <div className="font-medium text-primary">{task.summary}</div>
                  <Badge>{task.priority}</Badge>
                </div>
                <div className="mt-2 text-sm text-secondary">{task.description}</div>
              </div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <div className="flex items-center gap-3">
              <Inbox className="h-5 w-5 text-accent" />
              <CardTitle>Unified Inbox</CardTitle>
            </div>
            <CardDescription>Email, X, and LinkedIn copilot work in one place.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {dashboard.inboxThreads.map((thread) => (
              <div key={thread.id} className="rounded-2xl border border-border bg-primary p-4">
                <div className="flex items-center justify-between gap-3">
                  <div className="font-medium text-primary">{thread.title}</div>
                  <Badge>{thread.channel}</Badge>
                </div>
                <div className="mt-2 text-sm text-secondary">
                  {thread.unreadCount} unread · {new Date(thread.lastMessageAt).toLocaleString()}
                </div>
              </div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <div className="flex items-center gap-3">
              <Target className="h-5 w-5 text-accent" />
              <CardTitle>Pipeline</CardTitle>
            </div>
            <CardDescription>Qualified deals tied to offers and projects.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {dashboard.opportunities.map((opportunity) => (
              <div key={opportunity.id} className="rounded-2xl border border-border bg-primary p-4">
                <div className="flex items-center justify-between gap-3">
                  <div className="font-medium text-primary">{opportunity.name}</div>
                  <Badge>{opportunity.stage}</Badge>
                </div>
                <div className="mt-2 text-sm text-secondary">
                  {opportunity.nextStep} · ${opportunity.annualValue?.toLocaleString() ?? '0'}
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      </section>

      <section className="mt-10 grid gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <div className="flex items-center gap-3">
              <UserRound className="h-5 w-5 text-accent" />
              <CardTitle>Contacts</CardTitle>
            </div>
            <CardDescription>Cross-project people memory.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {dashboard.contacts.map((contact) => (
              <div key={contact.id} className="rounded-2xl border border-border bg-primary p-4">
                <div className="flex items-center justify-between gap-3">
                  <div className="font-medium text-primary">{contact.fullName}</div>
                  <Badge>{contact.lifecycle}</Badge>
                </div>
                <div className="mt-2 text-sm text-secondary">
                  {contact.jobTitle ?? contact.email ?? 'Unknown role'}
                </div>
              </div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <div className="flex items-center gap-3">
              <Building2 className="h-5 w-5 text-accent" />
              <CardTitle>Companies</CardTitle>
            </div>
            <CardDescription>Accounts and brand context.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {dashboard.companies.map((company) => (
              <div key={company.id} className="rounded-2xl border border-border bg-primary p-4">
                <div className="flex items-center justify-between gap-3">
                  <div className="font-medium text-primary">{company.name}</div>
                  <div className="flex items-center gap-2">
                    {company.tags.slice(0, 2).map((tag) => (
                      <Badge key={tag}>{tag}</Badge>
                    ))}
                  </div>
                </div>
                <div className="mt-2 text-sm text-secondary">{company.notes}</div>
              </div>
            ))}
          </CardContent>
        </Card>
      </section>

      <section className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <Card>
          <CardHeader>
            <div className="flex items-center gap-3">
              <Briefcase className="h-5 w-5 text-accent" />
              <CardTitle>Projects</CardTitle>
            </div>
          </CardHeader>
          <CardContent className="space-y-2 text-sm text-secondary">
            {dashboard.projects.map((project) => (
              <div key={project.id}>{project.name}</div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Brands</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-sm text-secondary">
            {dashboard.brands.map((brand) => (
              <div key={brand.id}>{brand.name}</div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Offers</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-sm text-secondary">
            {dashboard.offers.map((offer) => (
              <div key={offer.id}>{offer.name}</div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Sequences</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-sm text-secondary">
            {dashboard.sequences.map((sequence) => (
              <div key={sequence.id}>{sequence.name}</div>
            ))}
          </CardContent>
        </Card>
      </section>
    </main>
  );
}
